github.com:
    users:
        christc4:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: christc4
